# Generated by Django 5.1.1 on 2025-01-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_description_professionalexperience_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalexperience',
            name='proof_link',
            field=models.URLField(blank=True),
        ),
    ]
