# Generated by Django 5.1.1 on 2025-01-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='subject_image',
            field=models.ImageField(blank=True, null=True, upload_to='newsletters'),
        ),
    ]
