# Generated by Django 5.1.1 on 2024-12-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('subject', models.CharField(max_length=255)),
                ('sender_email', models.EmailField(max_length=254)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyée')], default='draft', max_length=10)),
                ('preview_url', models.URLField(blank=True, null=True)),
                ('subscribers', models.ManyToManyField(to='newsletter.subscriber')),
            ],
        ),
    ]
