# Generated by Django 5.1.1 on 2025-01-20 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_newsletter_subject_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='subject_image',
        ),
    ]
