# Generated by Django 5.1.1 on 2024-12-06 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_subscriber_is_active_subscriber_unsubscribe_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='sender_email',
        ),
    ]
