# Generated by Django 5.1.1 on 2025-01-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('summary', models.TextField()),
                ('link', models.URLField()),
                ('category', models.CharField(choices=[('dev', 'Development'), ('cyber', 'Cybersecurity'), ('ia', 'Artificial Intelligence'), ('math', 'Mathematics'), ('elec', 'Electronic')], default='dev', max_length=50)),
                ('number_read', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
