# Generated by Django 5.1.1 on 2025-01-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='in_progress', max_length=20),
        ),
    ]
