# Generated by Django 5.1.1 on 2025-01-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready'), ('in_progress', 'In Progress'), ('aborted', 'Aborted')], default='in_progress', max_length=20),
        ),
    ]
