# Generated by Django 5.1.1 on 2024-11-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcomment',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
