# Generated by Django 5.1.1 on 2024-12-05 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectcomment_is_public'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectComment',
        ),
    ]
