# Generated by Django 5.1.1 on 2024-12-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_delete_projectcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='number_read',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
