# Generated by Django 5.1.1 on 2024-12-06 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_number_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='likes_count',
        ),
    ]
