# Generated by Django 5.1.1 on 2024-12-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_project_likes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Développement', 'dev'), ('Cybersécurité', 'cyber'), ('Intelligence Artificielle', 'ia'), ('Mathématiques', 'math'), ('Électronique', 'elec')], default='Développement', max_length=50),
        ),
    ]
