# Generated by Django 5.1.1 on 2024-12-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('dev', 'Development'), ('cyber', 'Cybersecurity'), ('ia', 'Artificial Intelligence'), ('math', 'Mathematics'), ('elec', 'Electronic')], default='dev', max_length=50),
        ),
    ]
