# Generated by Django 5.1.1 on 2025-01-17 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpostsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostsection',
            name='summary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.summary'),
        ),
    ]
