# Generated by Django 5.1.1 on 2024-11-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='comments_count',
        ),
    ]
