# Generated by Django 5.1.1 on 2025-01-17 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpostsection_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpostsection',
            old_name='section',
            new_name='section_content',
        ),
        migrations.AlterField(
            model_name='blogpostsection',
            name='summary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='blog.summary'),
        ),
    ]
