# Generated by Django 5.1.1 on 2024-11-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
