# Generated by Django 5.1.1 on 2025-01-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_section_blogpostsection_section_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
