# Generated by Django 5.1.1 on 2024-12-05 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogcomment_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='links',
            new_name='summary_links',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='likes_count',
        ),
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
