# Generated by Django 5.1.1 on 2024-12-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_links_blogpost_summary_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='number_read',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
