# Generated by Django 5.1.1 on 2024-12-07 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpost_number_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='summary_links',
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('summary_links', models.JSONField(default=list)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='blog.blogpost')),
            ],
        ),
    ]
