# Generated by Django 5.1.1 on 2025-01-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpost_link_alter_summary_summary_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='outline',
        ),
        migrations.AddField(
            model_name='summary',
            name='is_outline',
            field=models.BooleanField(default=False),
        ),
    ]
