# Generated by Django 5.1.1 on 2024-12-07 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_blogpost_summary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='summary_links',
            new_name='summary_link',
        ),
    ]
