# Generated by Django 5.1.1 on 2025-01-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_blogpost_outline_summary_is_outline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='is_outline',
        ),
        migrations.AddField(
            model_name='blogpostsection',
            name='is_outline',
            field=models.BooleanField(default=False),
        ),
    ]
