# Generated by Django 5.1.1 on 2024-12-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_summary_links_summary_summary_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='summary_link',
            field=models.CharField(max_length=300),
        ),
    ]
