# Generated by Django 5.1.1 on 2025-01-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_summary_is_outline_blogpostsection_is_outline'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='illustration',
            field=models.ImageField(blank=True, null=True, upload_to='illustrations/'),
        ),
    ]
