# Generated by Django 5.1.1 on 2024-12-07 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_summary_summary_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='blog',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='blog.blogpost'),
        ),
    ]
